angular.module('ethExplorer')
    .controller('transactionInfosCtrl', function ($rootScope, $scope, $location, $routeParams,$q) {

       var web3 = $rootScope.web3;
       var abiDecoder = $rootScope.abiDecoder;

        $scope.init=function()
        {
            $scope.txId=$routeParams.transactionId;

            if($scope.txId!==undefined) { // add a test to check if it match tx paterns to avoid useless API call, clients are not obliged to come from the search form...

                getTransactionInfos()
                    .then(function(result){
                        //TODO Refactor this logic, asynchron calls + services....
                        var number = web3.eth.blockNumber;

                    $scope.result = result;

                    if(result.blockHash!==undefined){
                        $scope.blockHash = result.blockHash;
                    }
                    else{
                        $scope.blockHash ='pending';
                    }
                    if(result.blockNumber!==undefined){
                        $scope.blockNumber = result.blockNumber;
                    }
                    else{
                        $scope.blockNumber ='pending';
                    }
                    $scope.from = result.from;
                    $scope.gas = result.gas;
                    $scope.gasUsed = result.gasUsed;
                    $scope.contractAddress = result.contractAddress;
                    $scope.gasPrice = result.gasPrice.c[0] + " WEI";
                    $scope.hash = result.hash;
                    $scope.input = result.input; // that's a string
                    $scope.decoded = decodeData(result.input);
                    $scope.nonce = result.nonce;
                    $scope.to = result.to;
                    $scope.transactionIndex = result.transactionIndex;
                    $scope.ethValue = result.value.c[0] / 10000;
                    console.log(result);
                    $scope.txprice = (result.gas * result.gasPrice)/1000000000000000000 + " ETH";
                    if($scope.blockNumber!==undefined){
                        $scope.conf = number - $scope.blockNumber;
                        if($scope.conf===0){
                            $scope.conf='unconfirmed'; //TODO change color button when unconfirmed... ng-if or ng-class
                        }
                    }
                        //TODO Refactor this logic, asynchron calls + services....
                    if($scope.blockNumber!==undefined){
                        var info = web3.eth.getBlock($scope.blockNumber);
                        if(info!==undefined){
                            $scope.time = info.timestamp + '000';
                        }
                    }

                });

            }



            else{
                $location.path("/"); // add a trigger to display an error message so user knows he messed up with the TX number
            }


            function getTransactionInfos(){
                var deferred = $q.defer();

                web3.eth.getTransaction($scope.txId,function(error, result) {
                    if(!error){
                        web3.eth.getTransactionReceipt($scope.txId,function(err2, receipt) {
                            if(!err2) {
                                for (var attrname in receipt) { result[attrname] = receipt[attrname]; }
                            }
                            deferred.resolve(result);
                        });
                    }
                    else{
                        deferred.reject(error);
                    }
                });
                return deferred.promise;

            }

            function decodeData(data) {
              // TODO: how could we read ABIs generated by truffle? (build/contracts )
                abiDecoder.addABI(
                  [ { "constant": true, "inputs": [ { "name": "_roundId", "type": "uint256" } ], "name": "getWinnablePot", "outputs": [ { "name": "_winnablePot", "type": "uint256" } ], "payable": false, "type": "function" }, { "constant": true, "inputs": [], "name": "latestRoundId", "outputs": [ { "name": "_roundId", "type": "uint256" } ], "payable": false, "type": "function" }, { "constant": false, "inputs": [ { "name": "_new", "type": "address" } ], "name": "setOwner", "outputs": [], "payable": false, "type": "function" }, { "constant": true, "inputs": [], "name": "getGameInfo", "outputs": [ { "name": "_roundsCount", "type": "uint256" }, { "name": "_latestRoundId", "type": "uint256" }, { "name": "_nextRoundLength", "type": "uint256" }, { "name": "_nextRoundRequiredBetAmount", "type": "uint256" }, { "name": "_nextRoundFee", "type": "uint256" } ], "payable": false, "type": "function" }, { "constant": false, "inputs": [ { "name": "forceClose", "type": "bool" } ], "name": "checkAndCloseRound", "outputs": [ { "name": "result", "type": "int16" } ], "payable": false, "type": "function" }, { "constant": false, "inputs": [ { "name": "queryId", "type": "bytes32" }, { "name": "result", "type": "string" } ], "name": "__callback", "outputs": [], "payable": false, "type": "function" }, { "constant": false, "inputs": [ { "name": "myid", "type": "bytes32" }, { "name": "result", "type": "string" }, { "name": "proof", "type": "bytes" } ], "name": "__callback", "outputs": [], "payable": false, "type": "function" }, { "constant": true, "inputs": [ { "name": "roundId", "type": "uint256" }, { "name": "value", "type": "uint256" } ], "name": "verifyBet", "outputs": [ { "name": "result", "type": "uint8" } ], "payable": false, "type": "function" }, { "constant": false, "inputs": [ { "name": "roundId", "type": "uint256" }, { "name": "encryptedBet", "type": "string" } ], "name": "placeBet", "outputs": [ { "name": "queryId", "type": "bytes32" } ], "payable": true, "type": "function" }, { "constant": true, "inputs": [ { "name": "roundId", "type": "uint256" } ], "name": "getRequiredBetAmount", "outputs": [ { "name": "ret", "type": "uint256" } ], "payable": false, "type": "function" }, { "constant": true, "inputs": [ { "name": "_dataSource", "type": "string" } ], "name": "getOraclizePrice", "outputs": [ { "name": "", "type": "uint256" } ], "payable": false, "type": "function" }, { "constant": true, "inputs": [ { "name": "roundId", "type": "uint256" } ], "name": "getRoundInfo", "outputs": [ { "name": "_isActive", "type": "bool" }, { "name": "_requiredBetAmount", "type": "uint256" }, { "name": "_revealTime", "type": "uint256" }, { "name": "_roundLength", "type": "uint256" }, { "name": "_betCount", "type": "uint256" }, { "name": "_revealedBetCount", "type": "uint256" }, { "name": "_unReveleadBetCount", "type": "uint256" }, { "name": "_winningAddress", "type": "address" }, { "name": "_smallestNumber", "type": "uint256" }, { "name": "_winnablePot", "type": "uint256" }, { "name": "_fee", "type": "uint256" } ], "payable": false, "type": "function" }, { "constant": false, "inputs": [ { "name": "_nextRoundRequiredBetAmount", "type": "uint256" } ], "name": "setNextRoundRequiredBetAmount", "outputs": [], "payable": false, "type": "function" }, { "constant": true, "inputs": [], "name": "owner", "outputs": [ { "name": "", "type": "address" } ], "payable": false, "type": "function" }, { "constant": true, "inputs": [ { "name": "_roundId", "type": "uint256" } ], "name": "getFeeAmount", "outputs": [ { "name": "_feeAmount", "type": "uint256" } ], "payable": false, "type": "function" }, { "constant": false, "inputs": [], "name": "startNewRound", "outputs": [ { "name": "newRoundId", "type": "uint256" } ], "payable": false, "type": "function" }, { "constant": true, "inputs": [ { "name": "roundId", "type": "uint256" }, { "name": "playerAddress", "type": "address" } ], "name": "getBet", "outputs": [ { "name": "_didBet", "type": "bool" }, { "name": "_betNumber", "type": "uint256" }, { "name": "_didWin", "type": "bool" } ], "payable": false, "type": "function" }, { "constant": true, "inputs": [ { "name": "_roundId", "type": "uint256" } ], "name": "getTotalPot", "outputs": [ { "name": "_totalPot", "type": "uint256" } ], "payable": false, "type": "function" }, { "constant": false, "inputs": [ { "name": "_nextRoundLength", "type": "uint256" } ], "name": "setNextRoundLength", "outputs": [], "payable": false, "type": "function" }, { "constant": false, "inputs": [ { "name": "_nextRoundFee", "type": "uint32" } ], "name": "setNextRoundFee", "outputs": [], "payable": false, "type": "function" }, { "inputs": [], "payable": true, "type": "constructor" }, { "payable": true, "type": "fallback" }, { "anonymous": false, "inputs": [ { "indexed": true, "name": "_roundId", "type": "uint256" }, { "indexed": true, "name": "_from", "type": "address" }, { "indexed": false, "name": "_queryId", "type": "bytes32" } ], "name": "e_betPlaced", "type": "event" }, { "anonymous": false, "inputs": [ { "indexed": true, "name": "_roundId", "type": "uint256" }, { "indexed": true, "name": "_from", "type": "address" }, { "indexed": false, "name": "_queryId", "type": "bytes32" }, { "indexed": false, "name": "_betNumber", "type": "uint256" } ], "name": "e_betRevealed", "type": "event" }, { "anonymous": false, "inputs": [ { "indexed": true, "name": "_roundId", "type": "uint256" }, { "indexed": false, "name": "_winnerAddress", "type": "address" }, { "indexed": false, "name": "_winningNumber", "type": "uint256" }, { "indexed": false, "name": "_numberOfBets", "type": "uint256" }, { "indexed": false, "name": "_numberOfUnRevealedBets", "type": "uint256" }, { "indexed": false, "name": "_numberOfInvalidBets", "type": "uint256" } ], "name": "e_roundClosed", "type": "event" }, { "anonymous": false, "inputs": [ { "indexed": true, "name": "_roundId", "type": "uint256" }, { "indexed": false, "name": "_requiredBetAmount", "type": "uint256" }, { "indexed": false, "name": "_revealTime", "type": "uint256" } ], "name": "e_roundStarted", "type": "event" }, { "anonymous": false, "inputs": [ { "indexed": false, "name": "_errorMsg", "type": "string" } ], "name": "e_error", "type": "event" }, { "anonymous": false, "inputs": [ { "indexed": true, "name": "_from", "type": "address" }, { "indexed": false, "name": "_amount", "type": "uint256" } ], "name": "e_fundsReceived", "type": "event" }, { "anonymous": false, "inputs": [ { "indexed": true, "name": "_roundId", "type": "uint256" }, { "indexed": false, "name": "_settingName", "type": "string" }, { "indexed": false, "name": "_oldValue", "type": "uint256" }, { "indexed": false, "name": "_newValue", "type": "uint256" } ], "name": "e_settingChange", "type": "event" }, { "anonymous": false, "inputs": [ { "indexed": true, "name": "old", "type": "address" }, { "indexed": true, "name": "current", "type": "address" } ], "name": "NewOwner", "type": "event" } ]);
                var decoded = abiDecoder.decodeMethod(data);
                return JSON.stringify(decoded, null, 4);
            }

        };
        $scope.init();
        console.log($scope.result);

    });
